import js from "@eslint/js";
import typescript from "@typescript-eslint/eslint-plugin";
import typescriptParser from "@typescript-eslint/parser";
import nextPlugin from "@next/eslint-plugin-next";
import react from "eslint-plugin-react";
import reactHooks from "eslint-plugin-react-hooks";
import unusedImports from "eslint-plugin-unused-imports";
import oxlint from "eslint-plugin-oxlint";

// Build ESLint config from oxlint config to disable rules oxlint handles
const oxlintConfigs = oxlint.buildFromOxlintConfigFile(".oxlintrc.json");

// Type-aware rules that require TypeScript type checking (projectService: true).
// oxlint handles these, so we disable them in ESLint and skip building the full
// type graph — this is the main speed optimisation.
const oxlintTypeAwareRulesConfig = {
  name: "oxlint/type-aware-rules",
  files: ["**/*.{ts,tsx}"],
  languageOptions: {
    parserOptions: {
      projectService: false,
    },
  },
  rules: {
    "@typescript-eslint/await-thenable": "off",
    "@typescript-eslint/no-floating-promises": "off",
    "@typescript-eslint/no-misused-promises": "off",
    "@typescript-eslint/no-unnecessary-condition": "off",
    "@typescript-eslint/no-unnecessary-type-assertion": "off",
    "@typescript-eslint/prefer-nullish-coalescing": "off",
    "@typescript-eslint/prefer-optional-chain": "off",
    "@typescript-eslint/restrict-template-expressions": "off",
    "@typescript-eslint/switch-exhaustiveness-check": "off",
    "@typescript-eslint/no-redundant-type-constituents": "off",
    "@typescript-eslint/no-duplicate-type-constituents": "off",
    "@typescript-eslint/no-shadow": "off",
    "@typescript-eslint/require-await": "off",
    "@typescript-eslint/return-await": "off",
    "no-undef": "off",
  },
};

export default [
  // Global ignores
  {
    ignores: [
      ".next/**",
      "out/**",
      "node_modules/**",
      "src/lib/api.gen.ts", // generated — do not lint
      "next-env.d.ts", // generated by Next.js
    ],
  },

  // TypeScript source files
  {
    files: ["**/*.{ts,tsx}"],
    plugins: {
      "@typescript-eslint": typescript,
      "unused-imports": unusedImports,
    },
    languageOptions: {
      parser: typescriptParser,
      parserOptions: {
        ecmaVersion: "latest",
        sourceType: "module",
        projectService: true,
      },
      globals: {
        console: "readonly",
        process: "readonly",
        window: "readonly",
        document: "readonly",
        fetch: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        URL: "readonly",
        URLSearchParams: "readonly",
        RequestInit: "readonly",
        ReturnType: "readonly",
        React: "readonly",
        NodeJS: "readonly",
      },
    },
    rules: {
      ...js.configs.recommended.rules,
      ...typescript.configs.recommended.rules,

      // Unused imports/vars — errors (keep code clean)
      "unused-imports/no-unused-imports": "error",
      "unused-imports/no-unused-vars": [
        "warn",
        {
          vars: "all",
          varsIgnorePattern: "^_",
          args: "after-used",
          argsIgnorePattern: "^_",
        },
      ],
      "@typescript-eslint/no-unused-vars": "off", // handled by unused-imports

      // Type safety
      "@typescript-eslint/no-explicit-any": "warn",
      "@typescript-eslint/no-non-null-assertion": "warn",
      "@typescript-eslint/consistent-type-imports": ["warn", { prefer: "type-imports" }],

      // Async/promise correctness
      "@typescript-eslint/no-floating-promises": "error",
      "@typescript-eslint/no-misused-promises": "error",
      "@typescript-eslint/await-thenable": "error",

      // Code quality
      "prefer-const": "error",
      "no-console": ["warn", { allow: ["warn", "error"] }],
      eqeqeq: ["error", "always", { null: "ignore" }],
      "no-eval": "error",

      // Disable rules that TypeScript already handles
      "no-undef": "off",
      "no-redeclare": "off",

      // Too strict for data-fetching patterns (polling, SSR hydration)
      "react-hooks/set-state-in-effect": "off",
      // React Compiler hint — not applicable to this project
      "react-compiler/react-compiler": "off",
    },
  },

  // React + Next.js files
  {
    files: ["src/**/*.{ts,tsx}"],
    plugins: {
      react,
      "react-hooks": reactHooks,
      "@next/next": nextPlugin,
    },
    languageOptions: {
      parserOptions: {
        ecmaFeatures: { jsx: true },
      },
    },
    rules: {
      ...react.configs.recommended.rules,
      ...reactHooks.configs.recommended.rules,

      // React
      "react/react-in-jsx-scope": "off", // Not needed in Next.js
      "react/prop-types": "off", // TypeScript handles this
      "react/no-unescaped-entities": "off", // Too noisy
      "react/display-name": "warn",
      "react/self-closing-comp": "error",
      "react/jsx-no-useless-fragment": "error",
      "react/no-children-prop": "error",
      "react/hook-use-state": "error",
      "react/jsx-no-leaked-render": ["error", { validStrategies: ["ternary", "coerce"] }],

      // React hooks
      "react-hooks/rules-of-hooks": "error",
      "react-hooks/exhaustive-deps": "error",
      "react-hooks/set-state-in-effect": "off", // Too strict for polling/hydration patterns

      // Next.js
      "@next/next/no-html-link-for-pages": "error",
      "@next/next/no-img-element": "error",
      "@next/next/no-sync-scripts": "error",
    },
    settings: {
      react: { version: "detect" },
      next: { rootDir: "." },
    },
  },

  // Disable rules that oxlint handles (oxlint runs first, ~100x faster).
  // Built dynamically from .oxlintrc.json — must come last to override previous configs.
  ...oxlintConfigs,
  oxlintTypeAwareRulesConfig,

  // Re-enable Next.js rules that eslint-plugin-oxlint incorrectly disables
  // (oxlint doesn't have Next.js-specific rules, so ESLint should still enforce them).
  {
    files: ["src/**/*.{ts,tsx}"],
    plugins: {
      "@next/next": nextPlugin,
    },
    rules: {
      "@next/next/no-html-link-for-pages": "error",
      "@next/next/no-img-element": "error",
      "@next/next/no-sync-scripts": "error",
    },
    settings: {
      next: { rootDir: "." },
    },
  },
];
